spring:
  application:
    name: base_spring_boot
  datasource:
    url: jdbc:mysql://localhost:3306/cinema_db?createDatabaseIfNotExist=true
    username: root
    password: 0359977983V@n
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret:
    key:  "Ascmkkqdnmsdfrtgsyuhidj21ue120938219321ndsad2024SuperSecretKey!!"
  expired:
    access: 864000

server:
  port: 6789